# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiaBu(object):
    def setupUi(self, DiaBu):
        DiaBu.setObjectName("DiaBu")
        DiaBu.resize(310, 223)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/imagenes/shul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DiaBu.setWindowIcon(icon)
        DiaBu.setStyleSheet("background-color:  rgba(39,37,37);")
        self.textBrowser = QtWidgets.QTextBrowser(DiaBu)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 271, 171))
        self.textBrowser.setStyleSheet("color: rgb(229, 9, 127);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(50,48,48); \n"
"border:solid;\n"
"border:0px;\n"
"border-radius: 10px;\n"
"padding-left:30px;")
        self.textBrowser.setObjectName("textBrowser")
        self.acomlab_1 = QtWidgets.QLabel(DiaBu)
        self.acomlab_1.setGeometry(QtCore.QRect(30, 40, 16, 171))
        self.acomlab_1.setStyleSheet("/*border-radius:10px;*/\n"
"/*background-image: url(:/imagenes/imagenes/triangulo.png);*/\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(50,48,48); \n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_1.setText("")
        self.acomlab_1.setObjectName("acomlab_1")
        self.acom_1 = QtWidgets.QWidget(DiaBu)
        self.acom_1.setGeometry(QtCore.QRect(20, 40, 21, 171))
        self.acom_1.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_1.setObjectName("acom_1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.acom_1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.barblack_2 = QtWidgets.QGraphicsView(DiaBu)
        self.barblack_2.setGeometry(QtCore.QRect(0, 0, 331, 31))
        self.barblack_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barblack_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.barblack_2.setStyleSheet("border-style: solid;\n"
"\n"
"border-left: none;\n"
"border-right: none;\n"
"border-top: none;\n"
"border-bottom: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 3px;\n"
"border-color: rgba(9, 9, 9);\n"
"background-color: rgba(9, 9, 9); \n"
"color: rgb(229, 9, 127);\n"
"/*border-radius: 5px;*/\n"
"padding-top:3px;\n"
"padding-left:50px;")
        self.barblack_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barblack_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.barblack_2.setObjectName("barblack_2")
        self.pushrelclose_1 = QtWidgets.QPushButton(DiaBu)
        self.pushrelclose_1.setGeometry(QtCore.QRect(270, 0, 41, 31))
        self.pushrelclose_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushrelclose_1.setAcceptDrops(True)
        self.pushrelclose_1.setStyleSheet("background-image: url(:/imagenes/imagenes/ex.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushrelclose_1.setText("")
        self.pushrelclose_1.setObjectName("pushrelclose_1")
        self.somlab_3 = QtWidgets.QLabel(DiaBu)
        self.somlab_3.setGeometry(QtCore.QRect(140, 0, 41, 31))
        self.somlab_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_3.setObjectName("somlab_3")
        self.somlab_5 = QtWidgets.QLabel(DiaBu)
        self.somlab_5.setGeometry(QtCore.QRect(180, 10, 21, 16))
        self.somlab_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_5.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_5.setObjectName("somlab_5")
        self.textBrowser.raise_()
        self.acom_1.raise_()
        self.acomlab_1.raise_()
        self.barblack_2.raise_()
        self.pushrelclose_1.raise_()
        self.somlab_3.raise_()
        self.somlab_5.raise_()

        self.retranslateUi(DiaBu)
        self.pushrelclose_1.clicked.connect(DiaBu.close)
        QtCore.QMetaObject.connectSlotsByName(DiaBu)

    def retranslateUi(self, DiaBu):
        _translate = QtCore.QCoreApplication.translate
        DiaBu.setWindowTitle(_translate("DiaBu", "Principal Buttons"))
        self.textBrowser.setHtml(_translate("DiaBu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                          <img src=\":/imagenes/imagenes/carga2.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Home Interface.Buttom will open new menu.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        <img src=\":/imagenes/imagenes/boulas2.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clicking on it will open a pop-up window with</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">the payment details, in which we  can  enter </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">the user information or payment details. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    <img src=\":/imagenes/imagenes/estatics.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To make a purchase Release we had to have</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">entered the  user  data, a fter  entered,  we</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">press the  button  which  will  ope n a pop-up </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">window.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    <img src=\":/imagenes/imagenes/cedula.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To  make  a  Standard  purchase  we  had to</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">have  entered the user data,  after entered, </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">we   press  the   button   which   will  open  a</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pop-up window. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    <img src=\":/imagenes/imagenes/barras.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To  open  settings  we  have  to  press  the </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">button   which  opens  a   pop-up    window </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">where   we  select   the   proxy,   and  it  is </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">executed. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      <img src=\":/imagenes/imagenes/guardar5.png\" />      Save and close</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      <img src=\":/imagenes/imagenes/ojoabierto.png\" />     Active Head</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      <img src=\":/imagenes/imagenes/ojotachado.png\" />     Unheadless</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      <img src=\":/imagenes/imagenes/url.png\" />     Cods Button</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.somlab_3.setText(_translate("DiaBu", "Somnium"))
        self.somlab_5.setText(_translate("DiaBu", "1.0"))
import an_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiaBu = QtWidgets.QDialog()
    ui = Ui_DiaBu()
    ui.setupUi(DiaBu)
    DiaBu.show()
    sys.exit(app.exec_())
