# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proxis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Proxis(object):
    def setupUi(self, Proxis):
        Proxis.setObjectName("Proxis")
        Proxis.resize(451, 320)
        Proxis.setSizeIncrement(QtCore.QSize(728, 0))
        Proxis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/imagenes/shul.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Proxis.setWindowIcon(icon)
        Proxis.setStyleSheet("\n"
"color: rgb(229, 9, 127);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);")
        self.label_2 = QtWidgets.QLabel(Proxis)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 161, 16))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_2.setObjectName("label_2")
        self.proxitxt_1 = QtWidgets.QTextEdit(Proxis)
        self.proxitxt_1.setGeometry(QtCore.QRect(20, 90, 411, 171))
        self.proxitxt_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proxitxt_1.setMouseTracking(True)
        self.proxitxt_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.proxitxt_1.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:1px;\n"
"padding-left:30px;\n"
"padding-right:1px;\n"
"text-align: justify;\n"
"")
        self.proxitxt_1.setObjectName("proxitxt_1")
        self.barblack_2 = QtWidgets.QGraphicsView(Proxis)
        self.barblack_2.setGeometry(QtCore.QRect(-80, 0, 601, 31))
        self.barblack_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barblack_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.barblack_2.setStyleSheet("border-style: solid;\n"
"\n"
"border-left: none;\n"
"border-right: none;\n"
"border-top: none;\n"
"border-bottom: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 3px;\n"
"border-color: rgba(9, 9, 9);\n"
"background-color: rgba(9, 9, 9); \n"
"color: rgb(229, 9, 127);\n"
"/*border-radius: 5px;*/\n"
"padding-top:3px;\n"
"padding-left:50px;")
        self.barblack_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barblack_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.barblack_2.setObjectName("barblack_2")
        self.pushrelclose_1 = QtWidgets.QPushButton(Proxis)
        self.pushrelclose_1.setGeometry(QtCore.QRect(420, 0, 31, 31))
        self.pushrelclose_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushrelclose_1.setAcceptDrops(True)
        self.pushrelclose_1.setStyleSheet("background-image:url(:/imagenes/imagenes/ex.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushrelclose_1.setText("")
        self.pushrelclose_1.setObjectName("pushrelclose_1")
        self.somlab_4 = QtWidgets.QLabel(Proxis)
        self.somlab_4.setGeometry(QtCore.QRect(240, 10, 21, 16))
        self.somlab_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_4.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_4.setObjectName("somlab_4")
        self.somlab_3 = QtWidgets.QLabel(Proxis)
        self.somlab_3.setGeometry(QtCore.QRect(200, 0, 41, 31))
        self.somlab_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_3.setObjectName("somlab_3")
        self.acomlab_1 = QtWidgets.QLabel(Proxis)
        self.acomlab_1.setGeometry(QtCore.QRect(30, 90, 16, 171))
        self.acomlab_1.setStyleSheet("/*border-radius:10px;*/\n"
"/*background-image: url(:/imagenes/imagenes/triangulo.png);*/\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_1.setText("")
        self.acomlab_1.setObjectName("acomlab_1")
        self.acom_1 = QtWidgets.QWidget(Proxis)
        self.acom_1.setGeometry(QtCore.QRect(20, 90, 21, 171))
        self.acom_1.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_1.setObjectName("acom_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.acom_1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.nombrelab_11 = QtWidgets.QLabel(Proxis)
        self.nombrelab_11.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.nombrelab_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nombrelab_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"")
        self.nombrelab_11.setObjectName("nombrelab_11")
        self.headbutradio = QtWidgets.QRadioButton(Proxis)
        self.headbutradio.setGeometry(QtCore.QRect(300, 280, 82, 17))
        self.headbutradio.setObjectName("headbutradio")
        self.unheadbutradio_2 = QtWidgets.QRadioButton(Proxis)
        self.unheadbutradio_2.setGeometry(QtCore.QRect(360, 280, 82, 17))
        self.unheadbutradio_2.setObjectName("unheadbutradio_2")
        self.pushupdate_1 = QtWidgets.QPushButton(Proxis)
        self.pushupdate_1.setGeometry(QtCore.QRect(30, 270, 71, 31))
        self.pushupdate_1.setStyleSheet("font:9 9pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"\n"
"background-color: rgb(229, 9, 127);\n"
"border: 0px outset #E5097F ;  /* Grosor del Borde */  /* Color del Borde */\n"
"text-align: center;  /* Alineación del texto */\n"
"text-shadow: 2px 2px rgba(0,0,0,.1);\n"
"padding-left:0px;\n"
"padding-top:0px;\n"
"padding-bottom:2px;\n"
"border-radius: 8px;\n"
"")
        self.pushupdate_1.setObjectName("pushupdate_1")
        self.pushdelate_2 = QtWidgets.QPushButton(Proxis)
        self.pushdelate_2.setGeometry(QtCore.QRect(120, 270, 71, 31))
        self.pushdelate_2.setStyleSheet("font:9 9pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"\n"
"background-color: rgb(229, 9, 127);\n"
"border: 0px outset #E5097F ;  /* Grosor del Borde */  /* Color del Borde */\n"
"text-align: center;  /* Alineación del texto */\n"
"text-shadow: 2px 2px rgba(0,0,0,.1);\n"
"padding-left:0px;\n"
"padding-top:0px;\n"
"padding-bottom:2px;\n"
"border-radius: 8px;\n"
"")
        self.pushdelate_2.setObjectName("pushdelate_2")
        self.pushsave_3 = QtWidgets.QPushButton(Proxis)
        self.pushsave_3.setGeometry(QtCore.QRect(210, 270, 71, 31))
        self.pushsave_3.setStyleSheet("font:9 9pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"\n"
"background-color: rgb(229, 9, 127);\n"
"border: 0px outset #E5097F ;  /* Grosor del Borde */  /* Color del Borde */\n"
"text-align: center;  /* Alineación del texto */\n"
"text-shadow: 2px 2px rgba(0,0,0,.1);\n"
"padding-left:0px;\n"
"padding-top:0px;\n"
"padding-bottom:2px;\n"
"border-radius: 8px;\n"
"")
        self.pushsave_3.setObjectName("pushsave_3")
        self.label_2.raise_()
        self.proxitxt_1.raise_()
        self.barblack_2.raise_()
        self.pushrelclose_1.raise_()
        self.somlab_4.raise_()
        self.somlab_3.raise_()
        self.acom_1.raise_()
        self.acomlab_1.raise_()
        self.nombrelab_11.raise_()
        self.headbutradio.raise_()
        self.unheadbutradio_2.raise_()
        self.pushupdate_1.raise_()
        self.pushdelate_2.raise_()
        self.pushsave_3.raise_()

        self.retranslateUi(Proxis)
        self.pushrelclose_1.clicked.connect(Proxis.close)
        QtCore.QMetaObject.connectSlotsByName(Proxis)

    def retranslateUi(self, Proxis):
        _translate = QtCore.QCoreApplication.translate
        Proxis.setWindowTitle(_translate("Proxis", "Proxies"))
        self.label_2.setText(_translate("Proxis", "Proxy"))
        self.proxitxt_1.setHtml(_translate("Proxis", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.somlab_4.setText(_translate("Proxis", "1.0"))
        self.somlab_3.setText(_translate("Proxis", "Somnium"))
        self.nombrelab_11.setText(_translate("Proxis", "Proxies"))
        self.headbutradio.setText(_translate("Proxis", "Active"))
        self.unheadbutradio_2.setText(_translate("Proxis", "Disable"))
        self.pushupdate_1.setText(_translate("Proxis", "Update"))
        self.pushdelate_2.setText(_translate("Proxis", "Delate All"))
        self.pushsave_3.setText(_translate("Proxis", "Save"))
import an_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Proxis = QtWidgets.QWidget()
    ui = Ui_Proxis()
    ui.setupUi(Proxis)
    Proxis.show()
    sys.exit(app.exec_())
