# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'release.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_release_1(object):
    def setupUi(self, release_1):
        release_1.setObjectName("release_1")
        release_1.resize(530, 315)
        release_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/imagenes/shul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        release_1.setWindowIcon(icon)
        release_1.setStyleSheet("\n"
"color: rgb(229, 9, 127);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);")
        self.label_2 = QtWidgets.QLabel(release_1)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 161, 16))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_2.setObjectName("label_2")
        self.producttxt_1 = QtWidgets.QTextEdit(release_1)
        self.producttxt_1.setGeometry(QtCore.QRect(20, 120, 491, 31))
        self.producttxt_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.producttxt_1.setMouseTracking(True)
        self.producttxt_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.producttxt_1.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:3px;\n"
"padding-left:40px;\n"
"")
        self.producttxt_1.setObjectName("producttxt_1")
        self.label_3 = QtWidgets.QLabel(release_1)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(release_1)
        self.label_4.setGeometry(QtCore.QRect(200, 170, 71, 16))
        self.label_4.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_4.setObjectName("label_4")
        self.headradio_1 = QtWidgets.QRadioButton(release_1)
        self.headradio_1.setGeometry(QtCore.QRect(410, 180, 20, 51))
        self.headradio_1.setText("")
        self.headradio_1.setObjectName("headradio_1")
        self.graphicsView_4 = QtWidgets.QGraphicsView(release_1)
        self.graphicsView_4.setGeometry(QtCore.QRect(370, 180, 41, 51))
        self.graphicsView_4.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1  rgba(39, 37, 37);); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/ojoabierto.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.barblack_2 = QtWidgets.QGraphicsView(release_1)
        self.barblack_2.setGeometry(QtCore.QRect(-20, 0, 601, 31))
        self.barblack_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barblack_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.barblack_2.setStyleSheet("border-style: solid;\n"
"\n"
"border-left: none;\n"
"border-right: none;\n"
"border-top: none;\n"
"border-bottom: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 3px;\n"
"border-color: rgba(9, 9, 9);\n"
"background-color: rgba(9, 9, 9); \n"
"color: rgb(229, 9, 127);\n"
"/*border-radius: 5px;*/\n"
"padding-top:3px;\n"
"padding-left:50px;")
        self.barblack_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barblack_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.barblack_2.setObjectName("barblack_2")
        self.pushrelmin_1 = QtWidgets.QPushButton(release_1)
        self.pushrelmin_1.setGeometry(QtCore.QRect(470, 0, 31, 31))
        self.pushrelmin_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushrelmin_1.setStyleSheet("background-image: url(:/imagenes/imagenes/min.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushrelmin_1.setText("")
        self.pushrelmin_1.setObjectName("pushrelmin_1")
        self.pushrelclose_2 = QtWidgets.QPushButton(release_1)
        self.pushrelclose_2.setGeometry(QtCore.QRect(500, 0, 31, 31))
        self.pushrelclose_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushrelclose_2.setAcceptDrops(True)
        self.pushrelclose_2.setStyleSheet("background-image:url(:/imagenes/imagenes/ex.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushrelclose_2.setText("")
        self.pushrelclose_2.setObjectName("pushrelclose_2")
        self.somlab_4 = QtWidgets.QLabel(release_1)
        self.somlab_4.setGeometry(QtCore.QRect(280, 10, 21, 16))
        self.somlab_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_4.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_4.setObjectName("somlab_4")
        self.somlab_3 = QtWidgets.QLabel(release_1)
        self.somlab_3.setGeometry(QtCore.QRect(240, 0, 41, 31))
        self.somlab_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_3.setObjectName("somlab_3")
        self.acomlab_1 = QtWidgets.QLabel(release_1)
        self.acomlab_1.setGeometry(QtCore.QRect(30, 120, 31, 31))
        self.acomlab_1.setStyleSheet("/*border-radius:10px;*/\n"
"background-image: url(:/imagenes/imagenes/zapatilla.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_1.setText("")
        self.acomlab_1.setObjectName("acomlab_1")
        self.acom_1 = QtWidgets.QWidget(release_1)
        self.acom_1.setGeometry(QtCore.QRect(20, 120, 21, 31))
        self.acom_1.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_1.setObjectName("acom_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.acom_1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.nombrelab_11 = QtWidgets.QLabel(release_1)
        self.nombrelab_11.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.nombrelab_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nombrelab_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"")
        self.nombrelab_11.setObjectName("nombrelab_11")
        self.nombrelab_12 = QtWidgets.QLabel(release_1)
        self.nombrelab_12.setGeometry(QtCore.QRect(10, 60, 151, 21))
        self.nombrelab_12.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"")
        self.nombrelab_12.setObjectName("nombrelab_12")
        self.acom_2 = QtWidgets.QWidget(release_1)
        self.acom_2.setGeometry(QtCore.QRect(20, 190, 21, 31))
        self.acom_2.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_2.setObjectName("acom_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.acom_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.acom_3 = QtWidgets.QWidget(release_1)
        self.acom_3.setGeometry(QtCore.QRect(200, 190, 21, 31))
        self.acom_3.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_3.setObjectName("acom_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.acom_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.acomlab_3 = QtWidgets.QLabel(release_1)
        self.acomlab_3.setGeometry(QtCore.QRect(210, 190, 16, 31))
        self.acomlab_3.setStyleSheet("border-radius:10px;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_3.setText("")
        self.acomlab_3.setObjectName("acomlab_3")
        self.ciclestxt_3 = QtWidgets.QTextEdit(release_1)
        self.ciclestxt_3.setGeometry(QtCore.QRect(200, 190, 171, 31))
        self.ciclestxt_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ciclestxt_3.setMouseTracking(True)
        self.ciclestxt_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ciclestxt_3.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:3px;\n"
"padding-left:40px;\n"
"")
        self.ciclestxt_3.setObjectName("ciclestxt_3")
        self.unheadeadio_1 = QtWidgets.QRadioButton(release_1)
        self.unheadeadio_1.setGeometry(QtCore.QRect(470, 180, 20, 51))
        self.unheadeadio_1.setText("")
        self.unheadeadio_1.setObjectName("unheadeadio_1")
        self.graphicsView_5 = QtWidgets.QGraphicsView(release_1)
        self.graphicsView_5.setGeometry(QtCore.QRect(430, 180, 41, 51))
        self.graphicsView_5.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1  rgba(39, 37, 37);); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/ojotachado.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.pushbigbuy_1 = QtWidgets.QPushButton(release_1)
        self.pushbigbuy_1.setGeometry(QtCore.QRect(20, 250, 491, 41))
        self.pushbigbuy_1.setStyleSheet("border-radius:10px;\n"
"background-image: url(:/imagenes/imagenes/shul.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(30, 29, 29) ;\n"
"border-style: solid;\n"
"border-top: solid;\n"
"border-bottom:solid;\n"
"border-right: solid;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 1px;\n"
"padding-right: 3000px;\n"
"\n"
"")
        self.pushbigbuy_1.setText("")
        self.pushbigbuy_1.setObjectName("pushbigbuy_1")
        self.acomlab_2 = QtWidgets.QLabel(release_1)
        self.acomlab_2.setGeometry(QtCore.QRect(30, 190, 31, 31))
        self.acomlab_2.setStyleSheet("/*border-radius:10px;*/\n"
"background-image: url(:/imagenes/imagenes/talla.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_2.setText("")
        self.acomlab_2.setObjectName("acomlab_2")
        self.acomlab_4 = QtWidgets.QLabel(release_1)
        self.acomlab_4.setGeometry(QtCore.QRect(210, 190, 31, 31))
        self.acomlab_4.setStyleSheet("/*border-radius:10px;*/\n"
"background-image: url(:/imagenes/imagenes/punto.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_4.setText("")
        self.acomlab_4.setObjectName("acomlab_4")
        self.comboBox = QtWidgets.QComboBox(release_1)
        self.comboBox.setGeometry(QtCore.QRect(20, 190, 171, 31))
        self.comboBox.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:3px;\n"
"padding-left:40px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.raise_()
        self.ciclestxt_3.raise_()
        self.label_2.raise_()
        self.producttxt_1.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.headradio_1.raise_()
        self.graphicsView_4.raise_()
        self.barblack_2.raise_()
        self.pushrelmin_1.raise_()
        self.pushrelclose_2.raise_()
        self.somlab_4.raise_()
        self.somlab_3.raise_()
        self.acom_1.raise_()
        self.acomlab_1.raise_()
        self.nombrelab_11.raise_()
        self.nombrelab_12.raise_()
        self.acom_2.raise_()
        self.acom_3.raise_()
        self.acomlab_3.raise_()
        self.unheadeadio_1.raise_()
        self.graphicsView_5.raise_()
        self.pushbigbuy_1.raise_()
        self.acomlab_2.raise_()
        self.acomlab_4.raise_()

        self.retranslateUi(release_1)
        self.pushrelclose_2.clicked.connect(release_1.close)
        self.pushrelmin_1.clicked.connect(release_1.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(release_1)

    def retranslateUi(self, release_1):
        _translate = QtCore.QCoreApplication.translate
        release_1.setWindowTitle(_translate("release_1", "Release Buy"))
        self.label_2.setText(_translate("release_1", "Release Name"))
        self.producttxt_1.setHtml(_translate("release_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("release_1", "Size"))
        self.label_4.setText(_translate("release_1", "Cycles"))
        self.somlab_4.setText(_translate("release_1", "1.0"))
        self.somlab_3.setText(_translate("release_1", "Somnium"))
        self.nombrelab_11.setText(_translate("release_1", "Release Buy"))
        self.nombrelab_12.setText(_translate("release_1", "Footlocker.com"))
        self.ciclestxt_3.setHtml(_translate("release_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comboBox.setItemText(1, _translate("release_1", "XS"))
        self.comboBox.setItemText(2, _translate("release_1", "S"))
        self.comboBox.setItemText(3, _translate("release_1", "M"))
        self.comboBox.setItemText(4, _translate("release_1", "L"))
        self.comboBox.setItemText(5, _translate("release_1", "XL"))
        self.comboBox.setItemText(6, _translate("release_1", "XXL"))
        self.comboBox.setItemText(7, _translate("release_1", "3XL"))
        self.comboBox.setItemText(8, _translate("release_1", "05.0"))
        self.comboBox.setItemText(9, _translate("release_1", "05.5"))
        self.comboBox.setItemText(10, _translate("release_1", "06.0"))
        self.comboBox.setItemText(11, _translate("release_1", "06.5"))
        self.comboBox.setItemText(12, _translate("release_1", "07.0"))
        self.comboBox.setItemText(13, _translate("release_1", "07.5"))
        self.comboBox.setItemText(14, _translate("release_1", "08.0"))
        self.comboBox.setItemText(15, _translate("release_1", "08.5"))
        self.comboBox.setItemText(16, _translate("release_1", "09.0"))
        self.comboBox.setItemText(17, _translate("release_1", "09.5"))
        self.comboBox.setItemText(18, _translate("release_1", "10.0"))
        self.comboBox.setItemText(19, _translate("release_1", "10.5"))
        self.comboBox.setItemText(20, _translate("release_1", "11.0"))
        self.comboBox.setItemText(21, _translate("release_1", "11.5"))
        self.comboBox.setItemText(22, _translate("release_1", "12.0"))
        self.comboBox.setItemText(23, _translate("release_1", "13.0"))
        self.comboBox.setItemText(24, _translate("release_1", "14.0"))
        self.comboBox.setItemText(25, _translate("release_1", "15.0"))
import an_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    release_1 = QtWidgets.QWidget()
    ui = Ui_release_1()
    ui.setupUi(release_1)
    release_1.show()
    sys.exit(app.exec_())
