# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(510, 243)
        Settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Settings.setStyleSheet("\n"
"color: rgb(229, 9, 127);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);")
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 161, 16))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_2.setObjectName("label_2")
        self.serialtxt_1 = QtWidgets.QTextEdit(Settings)
        self.serialtxt_1.setGeometry(QtCore.QRect(20, 120, 471, 31))
        self.serialtxt_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serialtxt_1.setMouseTracking(True)
        self.serialtxt_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.serialtxt_1.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:3px;\n"
"padding-left:40px;\n"
"")
        self.serialtxt_1.setObjectName("serialtxt_1")
        self.label_3 = QtWidgets.QLabel(Settings)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color:  rgba(39, 37, 37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_3.setObjectName("label_3")
        self.barblack_2 = QtWidgets.QGraphicsView(Settings)
        self.barblack_2.setGeometry(QtCore.QRect(-20, 0, 601, 31))
        self.barblack_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barblack_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.barblack_2.setStyleSheet("border-style: solid;\n"
"\n"
"border-left: none;\n"
"border-right: none;\n"
"border-top: none;\n"
"border-bottom: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 3px;\n"
"border-color: rgba(9, 9, 9);\n"
"background-color: rgba(9, 9, 9); \n"
"color: rgb(229, 9, 127);\n"
"/*border-radius: 5px;*/\n"
"padding-top:3px;\n"
"padding-left:50px;")
        self.barblack_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barblack_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.barblack_2.setObjectName("barblack_2")
        self.pushsave_1 = QtWidgets.QPushButton(Settings)
        self.pushsave_1.setGeometry(QtCore.QRect(450, 0, 31, 31))
        self.pushsave_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushsave_1.setStyleSheet("background-image: url(:/imagenes/imagenes/guardar6.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushsave_1.setText("")
        self.pushsave_1.setObjectName("pushsave_1")
        self.pushrelclose_1 = QtWidgets.QPushButton(Settings)
        self.pushrelclose_1.setGeometry(QtCore.QRect(480, 0, 31, 31))
        self.pushrelclose_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushrelclose_1.setAcceptDrops(True)
        self.pushrelclose_1.setStyleSheet("background-image:url(:/imagenes/imagenes/ex.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color: rgba(9,9,9);")
        self.pushrelclose_1.setText("")
        self.pushrelclose_1.setObjectName("pushrelclose_1")
        self.somlab_4 = QtWidgets.QLabel(Settings)
        self.somlab_4.setGeometry(QtCore.QRect(280, 10, 21, 16))
        self.somlab_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_4.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_4.setObjectName("somlab_4")
        self.somlab_3 = QtWidgets.QLabel(Settings)
        self.somlab_3.setGeometry(QtCore.QRect(240, 0, 41, 31))
        self.somlab_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.somlab_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"background-color: rgb(9,9,9);\n"
"")
        self.somlab_3.setObjectName("somlab_3")
        self.acomlab_1 = QtWidgets.QLabel(Settings)
        self.acomlab_1.setGeometry(QtCore.QRect(30, 120, 31, 31))
        self.acomlab_1.setStyleSheet("/*border-radius:10px;*/\n"
"background-image: url(:/imagenes/imagenes/candado.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_1.setText("")
        self.acomlab_1.setObjectName("acomlab_1")
        self.acom_1 = QtWidgets.QWidget(Settings)
        self.acom_1.setGeometry(QtCore.QRect(20, 120, 21, 31))
        self.acom_1.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_1.setObjectName("acom_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.acom_1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.nombrelab_11 = QtWidgets.QLabel(Settings)
        self.nombrelab_11.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.nombrelab_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nombrelab_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(187, 181, 181));\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"padding-right: 0px;\n"
"padding-left: 0px;\n"
"")
        self.nombrelab_11.setObjectName("nombrelab_11")
        self.acom_2 = QtWidgets.QWidget(Settings)
        self.acom_2.setGeometry(QtCore.QRect(20, 190, 21, 31))
        self.acom_2.setStyleSheet("background-color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"")
        self.acom_2.setObjectName("acom_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.acom_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.chromiumtxt_2 = QtWidgets.QTextEdit(Settings)
        self.chromiumtxt_2.setGeometry(QtCore.QRect(20, 190, 471, 31))
        self.chromiumtxt_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chromiumtxt_2.setMouseTracking(True)
        self.chromiumtxt_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chromiumtxt_2.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 10px;\n"
"padding-top:3px;\n"
"padding-left:40px;\n"
"")
        self.chromiumtxt_2.setObjectName("chromiumtxt_2")
        self.acomlab_2 = QtWidgets.QLabel(Settings)
        self.acomlab_2.setGeometry(QtCore.QRect(30, 190, 31, 31))
        self.acomlab_2.setStyleSheet("/*border-radius:10px;*/\n"
"background-image: url(:/imagenes/imagenes/chrome.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"background-color:rgba(50,48,48);\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-bottom:none;\n"
"border-right: none;\n"
"border-color: rgba(229, 9, 127);\n"
"border-width: 5px;")
        self.acomlab_2.setText("")
        self.acomlab_2.setObjectName("acomlab_2")
        self.chromiumtxt_2.raise_()
        self.label_2.raise_()
        self.serialtxt_1.raise_()
        self.label_3.raise_()
        self.barblack_2.raise_()
        self.pushsave_1.raise_()
        self.pushrelclose_1.raise_()
        self.somlab_4.raise_()
        self.somlab_3.raise_()
        self.acom_1.raise_()
        self.acomlab_1.raise_()
        self.nombrelab_11.raise_()
        self.acom_2.raise_()
        self.acomlab_2.raise_()

        self.retranslateUi(Settings)
        self.pushrelclose_1.clicked.connect(Settings.close)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.label_2.setText(_translate("Settings", "Serial"))
        self.serialtxt_1.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Settings", "Chromium"))
        self.somlab_4.setText(_translate("Settings", "1.0"))
        self.somlab_3.setText(_translate("Settings", "Somnium"))
        self.nombrelab_11.setText(_translate("Settings", "Settings"))
        self.chromiumtxt_2.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import an_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
