# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaemergente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_1(object):
    def setupUi(self, popup_1):
        popup_1.setObjectName("popup_1")
        popup_1.setWindowModality(QtCore.Qt.NonModal)
        popup_1.resize(550, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(popup_1.sizePolicy().hasHeightForWidth())
        popup_1.setSizePolicy(sizePolicy)
        popup_1.setMinimumSize(QtCore.QSize(550, 400))
        popup_1.setMaximumSize(QtCore.QSize(550, 400))
        popup_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        popup_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        popup_1.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/imagenes/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/imagenes/imagenes/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        popup_1.setWindowIcon(icon)
        popup_1.setWindowOpacity(1.0)
        popup_1.setToolTipDuration(6)
        popup_1.setAutoFillBackground(False)
        popup_1.setStyleSheet("background-color:  rgba(39,37,37);\n"
"color: rgb(229, 9, 127);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.Nametxt_1 = QtWidgets.QTextEdit(popup_1)
        self.Nametxt_1.setGeometry(QtCore.QRect(10, 60, 261, 31))
        self.Nametxt_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nametxt_1.setMouseTracking(True)
        self.Nametxt_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Nametxt_1.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Nametxt_1.setObjectName("Nametxt_1")
        self.Emailtxt_3 = QtWidgets.QTextEdit(popup_1)
        self.Emailtxt_3.setGeometry(QtCore.QRect(10, 130, 321, 31))
        self.Emailtxt_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Emailtxt_3.setMouseTracking(True)
        self.Emailtxt_3.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Emailtxt_3.setObjectName("Emailtxt_3")
        self.Phonetxt_4 = QtWidgets.QTextEdit(popup_1)
        self.Phonetxt_4.setGeometry(QtCore.QRect(340, 130, 201, 31))
        self.Phonetxt_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Phonetxt_4.setMouseTracking(True)
        self.Phonetxt_4.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Phonetxt_4.setObjectName("Phonetxt_4")
        self.Addresstxt_5 = QtWidgets.QTextEdit(popup_1)
        self.Addresstxt_5.setGeometry(QtCore.QRect(10, 200, 381, 31))
        self.Addresstxt_5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Addresstxt_5.setMouseTracking(True)
        self.Addresstxt_5.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Addresstxt_5.setObjectName("Addresstxt_5")
        self.Aparttxt_6 = QtWidgets.QTextEdit(popup_1)
        self.Aparttxt_6.setGeometry(QtCore.QRect(400, 200, 141, 31))
        self.Aparttxt_6.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Aparttxt_6.setMouseTracking(True)
        self.Aparttxt_6.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Aparttxt_6.setObjectName("Aparttxt_6")
        self.Statetxt_7 = QtWidgets.QTextEdit(popup_1)
        self.Statetxt_7.setGeometry(QtCore.QRect(10, 270, 171, 31))
        self.Statetxt_7.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Statetxt_7.setMouseTracking(True)
        self.Statetxt_7.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Statetxt_7.setObjectName("Statetxt_7")
        self.Cardtxt_10 = QtWidgets.QTextEdit(popup_1)
        self.Cardtxt_10.setGeometry(QtCore.QRect(10, 340, 231, 31))
        self.Cardtxt_10.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cardtxt_10.setMouseTracking(True)
        self.Cardtxt_10.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Cardtxt_10.setObjectName("Cardtxt_10")
        self.Monthtxt_11 = QtWidgets.QTextEdit(popup_1)
        self.Monthtxt_11.setGeometry(QtCore.QRect(250, 340, 91, 31))
        self.Monthtxt_11.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Monthtxt_11.setMouseTracking(True)
        self.Monthtxt_11.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Monthtxt_11.setObjectName("Monthtxt_11")
        self.label = QtWidgets.QLabel(popup_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(229,9,127));\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(popup_1)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 211, 16))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(popup_1)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_4.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(popup_1)
        self.label_5.setGeometry(QtCore.QRect(340, 110, 71, 16))
        self.label_5.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(popup_1)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_6.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(popup_1)
        self.label_7.setGeometry(QtCore.QRect(400, 180, 61, 16))
        self.label_7.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(popup_1)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.label_8.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(popup_1)
        self.label_9.setGeometry(QtCore.QRect(190, 250, 31, 16))
        self.label_9.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(popup_1)
        self.label_10.setGeometry(QtCore.QRect(370, 250, 61, 16))
        self.label_10.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(popup_1)
        self.label_12.setGeometry(QtCore.QRect(10, 320, 71, 16))
        self.label_12.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(popup_1)
        self.label_13.setGeometry(QtCore.QRect(250, 320, 71, 16))
        self.label_13.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(popup_1)
        self.label_14.setGeometry(QtCore.QRect(450, 320, 31, 16))
        self.label_14.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_14.setObjectName("label_14")
        self.Lastxt_2 = QtWidgets.QTextEdit(popup_1)
        self.Lastxt_2.setGeometry(QtCore.QRect(280, 60, 261, 31))
        self.Lastxt_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Lastxt_2.setMouseTracking(True)
        self.Lastxt_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Lastxt_2.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Lastxt_2.setObjectName("Lastxt_2")
        self.Citytxt_8 = QtWidgets.QTextEdit(popup_1)
        self.Citytxt_8.setGeometry(QtCore.QRect(190, 270, 171, 31))
        self.Citytxt_8.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Citytxt_8.setMouseTracking(True)
        self.Citytxt_8.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Citytxt_8.setObjectName("Citytxt_8")
        self.Postaltxt_9 = QtWidgets.QTextEdit(popup_1)
        self.Postaltxt_9.setGeometry(QtCore.QRect(370, 270, 171, 31))
        self.Postaltxt_9.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Postaltxt_9.setMouseTracking(True)
        self.Postaltxt_9.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Postaltxt_9.setObjectName("Postaltxt_9")
        self.Yeartxt_12 = QtWidgets.QTextEdit(popup_1)
        self.Yeartxt_12.setGeometry(QtCore.QRect(350, 340, 91, 31))
        self.Yeartxt_12.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Yeartxt_12.setMouseTracking(True)
        self.Yeartxt_12.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Yeartxt_12.setObjectName("Yeartxt_12")
        self.Csctxt_13 = QtWidgets.QTextEdit(popup_1)
        self.Csctxt_13.setGeometry(QtCore.QRect(450, 340, 91, 31))
        self.Csctxt_13.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Csctxt_13.setMouseTracking(True)
        self.Csctxt_13.setStyleSheet("border-style: solid;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-width: 0px;\n"
"border-color: rgba(50,48,48);\n"
"background-color: rgba(50,48,48); \n"
"color: rgb(229, 9, 127);\n"
"border-radius: 5px;\n"
"padding-top:3px;\n"
"padding-left:30px;\n"
"")
        self.Csctxt_13.setObjectName("Csctxt_13")
        self.label_3 = QtWidgets.QLabel(popup_1)
        self.label_3.setGeometry(QtCore.QRect(280, 40, 211, 16))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(popup_1)
        self.label_15.setGeometry(QtCore.QRect(350, 320, 71, 16))
        self.label_15.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(39,37,37);\n"
"color: rgb(187,181,181);\n"
"padding-bottom: 0px")
        self.label_15.setObjectName("label_15")
        self.graphicsView = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.graphicsView.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/lol.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_2.setGeometry(QtCore.QRect(280, 60, 31, 31))
        self.graphicsView_2.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/lol.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 130, 31, 31))
        self.graphicsView_3.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image:url(:/imagenes/imagenes/carta.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_4.setGeometry(QtCore.QRect(340, 130, 31, 31))
        self.graphicsView_4.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/tel.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.graphicsView_5.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/dir.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_6.setGeometry(QtCore.QRect(400, 200, 31, 31))
        self.graphicsView_6.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/num.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_7.setGeometry(QtCore.QRect(10, 270, 31, 31))
        self.graphicsView_7.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/state.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_8.setGeometry(QtCore.QRect(190, 270, 31, 31))
        self.graphicsView_8.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/state.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_9.setGeometry(QtCore.QRect(370, 270, 31, 31))
        self.graphicsView_9.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/state.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_10.setGeometry(QtCore.QRect(10, 340, 31, 31))
        self.graphicsView_10.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/card.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.graphicsView_11 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_11.setGeometry(QtCore.QRect(250, 340, 31, 31))
        self.graphicsView_11.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/card.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.graphicsView_12 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_12.setGeometry(QtCore.QRect(350, 340, 31, 31))
        self.graphicsView_12.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/card.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.graphicsView_13 = QtWidgets.QGraphicsView(popup_1)
        self.graphicsView_13.setGeometry(QtCore.QRect(450, 340, 31, 31))
        self.graphicsView_13.setStyleSheet("border-style: solid;\n"
"border-width: 0px;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50,48,48)); \n"
"border-radius: 5px;\n"
"background-image: url(:/imagenes/imagenes/card.png);\n"
"background-repeat:no-repeat;\n"
"margin:10px;\n"
"")
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.pushclose_1 = QtWidgets.QPushButton(popup_1)
        self.pushclose_1.setGeometry(QtCore.QRect(520, 10, 21, 23))
        self.pushclose_1.setStyleSheet("background-color:  rgba(39,37,37);\n"
"background-image: url(:/imagenes/imagenes/equisgris.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-bottom:none;\n"
"border-right: solid;")
        self.pushclose_1.setText("")
        self.pushclose_1.setObjectName("pushclose_1")
        self.pushsave_1 = QtWidgets.QPushButton(popup_1)
        self.pushsave_1.setGeometry(QtCore.QRect(500, 10, 21, 23))
        self.pushsave_1.setStyleSheet("background-color:  rgba(39,37,37);\n"
"background-image: url(:/imagenes/imagenes/guardar6.png);\n"
"background-attachment: fixed;\n"
"background-position: center center;\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"border-style: solid;\n"
"border-top: none;\n"
"border-bottom:none;\n"
"border-right: solid;")
        self.pushsave_1.setText("")
        self.pushsave_1.setObjectName("pushsave_1")

        self.retranslateUi(popup_1)
        self.pushclose_1.clicked.connect(popup_1.close)
        QtCore.QMetaObject.connectSlotsByName(popup_1)

    def retranslateUi(self, popup_1):
        _translate = QtCore.QCoreApplication.translate
        popup_1.setWindowTitle(_translate("popup_1", "                                                              Somnium-Payment Details"))
        self.Nametxt_1.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Emailtxt_3.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Phonetxt_4.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Addresstxt_5.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Aparttxt_6.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Statetxt_7.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Cardtxt_10.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Monthtxt_11.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label.setText(_translate("popup_1", "Payment Details"))
        self.label_2.setText(_translate("popup_1", "First Name"))
        self.label_4.setText(_translate("popup_1", "E-mail Address "))
        self.label_5.setText(_translate("popup_1", "Phone Number"))
        self.label_6.setText(_translate("popup_1", "Street Address"))
        self.label_7.setText(_translate("popup_1", "Apartment"))
        self.label_8.setText(_translate("popup_1", "State"))
        self.label_9.setText(_translate("popup_1", "City"))
        self.label_10.setText(_translate("popup_1", "Postal Code"))
        self.label_12.setText(_translate("popup_1", "Card Number"))
        self.label_13.setText(_translate("popup_1", "Expiry Month"))
        self.label_14.setText(_translate("popup_1", "CsC"))
        self.Lastxt_2.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Citytxt_8.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Postaltxt_9.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Yeartxt_12.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Csctxt_13.setHtml(_translate("popup_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("popup_1", "Last Name"))
        self.label_15.setText(_translate("popup_1", "Expiry Year"))
import an_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    popup_1 = QtWidgets.QWidget()
    ui = Ui_popup_1()
    ui.setupUi(popup_1)
    popup_1.show()
    sys.exit(app.exec_())
